# Note: You must restart bin/webpack-dev-server for changes to take effect
development:
  source_entry_path: dist
  public_output_path: dist

  dev_server:
    # https: false
    host: localhost
    # port: 3035
    public: localhost:3035
